### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by MarkosKon** [mciastek/sal#28]
[Example repo](https://github.com/MarkosKon/sal-gatsby), run `yarn build`

I get the following error when I try to build with Gatsby. I'm not initializing sal, just importing it:

```
 WebpackError: ReferenceError: window is not defined

  - sal.js:1 Object../node_modules/sal.js/dist/sal.js [as js]
    node_modules/sal.js/dist/sal.js:1:187
```

The error points at column 187 of `dist/sal.js`. [This commit](https://github.com/mciastek/sal/commit/a0a0e4f38a2896dffb7dd22f12052f77ac6af2c0#diff-2a6d07eef8b10b84129b42424ed99327) added one more `window` at column 187.

**Comment by mciastek** [comment]
That's the issue with using sal.js on server side. I merged a fix #29 that will solve this it. Fetch v0.6.5 from NPM and let me know if it works.

**Comment by MarkosKon** [comment]
The additions are great, but I still get the error when I try to import sal.

I suggest adding to the `output` field of the webpack configuration the following line: 

```js
// webpack.config.js
module.exports = {
  output: {
    globalObject: 'this'
  }
}
```

Explanation in the webpacks docs: https://webpack.js.org/configuration/output/#outputglobalobject

I tried it locally it with npm link and it works. See if you like it.

**Comment by mciastek** [comment]
> The additions are great, but I still get the error when I try to import sal.
> 
> I suggest adding to the `output` field of the webpack configuration the following line:
> 
> ```js
> // webpack.config.js
> module.exports = {
>   output: {
>     globalObject: 'this'
>   }
> }
> ```
> 
> Explanation in the webpacks docs: https://webpack.js.org/configuration/output/#outputglobalobject
> 
> I tried it locally it with npm link and it works. See if you like it.

Looks nice! Probably that's missing. Would you like to create a PR with this fix?

**Comment by MarkosKon** [comment]
> Looks nice! Probably that's missing. Would you like to create a PR with this fix?

Yes, I would like that!

**Comment by mciastek** [comment]
Resolved by #30
